spring:
  config:
    activate:
      on-profile: local-stack

  datasource:
    url: jdbc:postgresql://database:5432/it_mentor_community_platform?currentSchema=telegram_bot_adapter
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092