server:
  port: 8087

spring:
  config:
    activate:
      on-profile: ide

  datasource:
    url: jdbc:postgresql://localhost:5432/it_mentor_community_platform
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:29092