server:
  port: 8087

spring:
  config:
    activate:
      on-profile: ide

  datasource:
    url: jdbc:postgresql://localhost:5432/it_mentor_community_platform?currentSchema=telegram_bot_adapter
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:29092

auth:
  username: username
  password: password

logging:
  level:
    org.springframework.security: DEBUG