name: Trigger E2E Tests

on:
  pull_request:
    branches:
      - staging
      - dev
  workflow_dispatch:

jobs:
  trigger-e2e:
    name: Trigger E2E Test in e2e repo
    runs-on: ubuntu-latest
    steps:
      - name: Get short SHA
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            FULL_SHA="${{ github.event.pull_request.head.sha }}"
          else
            FULL_SHA="${{ github.sha }}"
          fi
          echo "full_sha=$FULL_SHA" >> $GITHUB_OUTPUT
          echo "sha_short=$(echo $FULL_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Wait for build workflow to complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ steps.vars.outputs.full_sha }}
          check-name: 'Build and Push Docker image'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 15
          allowed-conclusions: success

      - name: Trigger E2E workflow and wait for result
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: it-mentor-community-platform
          repo: e2e-tests
          github_token: '${{ secrets.E2E_TRIGGER_TOKEN }}'
          workflow_file_name: ci.yml
          ref: dev
          client_payload: |
            {
              "telegram_bot_adapter_tag": "sha-${{ steps.vars.outputs.sha_short }}"
            }
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
          wait_interval: 15
